<?php
$s="i am vivek prajapati from madhi";
echo "<P><b><u>string length</u></b></P> ";
echo strlen($s);
echo "<br>";
echo "<P><b><u>woed count</u></b></P> ";
echo str_word_count($s);
echo "<br>";
echo "  <P><b><u> word possision</u></b></P> ";
echo strpos($s, "vivek");
echo "<br>";
echo " <P><b><u>to uppercase</u></b></P> ";
echo strtoupper($s);
echo "<br>";
echo "<p><b><u>to lowercase </u></b></p>";
echo strtolower($s);
echo "<br>";
echo "<p><b><u>string replace</u></b></p>";
echo str_replace("vivek", "yuvraj", $s."<br>");
echo "<p><b><u>do not changes acttual string</u></b></p>";
echo "$s <br>";
echo "<p><b><u>string reverse </u></b></p>";
echo strrev($s);
echo "<br>";
echo " <p><b><u>trimming a string</u></b></p>";
echo trim($s);
echo "<br>";
echo  "<P><b><u>string to array</u></b></P>";
$k= explode(" ", $s);
print_r($k);
echo "<br>";
echo "<P><b><u>string concate</u></b></P>";
$m="i am 20 y/o";
echo $s.$m;
echo "<br>";
echo "<P><b><u> concate with space</u></b></P>";
echo $s." ".$m,"\n";
echo "<br>";
echo "<P><b><u> slice oprations </u></b></P>";
echo substr($s, 6, 10);
echo "<br>";
echo substr($s, 6);
echo "<br>";
echo substr($s, -15, 10);
echo "<br>";
echo substr($s, 15, -10);
echo "<br>";
echo "<P><b><u> escape character </u></b></P>";
echo $p="hello \"how\tare you \"sir";
echo "<br>";
